.TH "AngledMultiText" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AngledMultiText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMultiText\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAngledMultiText\fP (\fBCanvas\fP *c, const \fBStyle\fP *s, float angle, float x, float y)"
.br
.ti -1c
.RI "void \fBrender\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
