.TH "BarChartWidget" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BarChartWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGraphWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBarChartWidget\fP (\fBCanvas\fP *c, \fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, double x, double y, double w, double h)"
.br
.ti -1c
.RI "void \fBsetBarWidth\fP (double width)"
.br
.ti -1c
.RI "void \fBsetBarColors\fP (const std::vector< glm::vec4 > &colors)"
.br
.ti -1c
.RI "void \fBsetValues\fP (const std::vector< double > &values)"
.br
.ti -1c
.RI "void \fBsetNames\fP (const std::vector< std::string > &names)"
.br
.ti -1c
.RI "void \fBcreateXAxis\fP (AxisType a=AxisType::TEXT) override"
.br
.ti -1c
.RI "void \fBcreateYAxis\fP (AxisType a) override"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
