.TH "Bezier" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bezier
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBezier\fP (float ax, float bx, float cx, float dx, float ay, float by, float cy, float dy, int n, bool end, const glm::vec4 &c={0, 0, 0, 1})"
.br
.ti -1c
.RI "float \fBgetax\fP () const"
.br
.ti -1c
.RI "float \fBgetay\fP () const"
.br
.ti -1c
.RI "float \fBgetbx\fP () const"
.br
.ti -1c
.RI "float \fBgetby\fP () const"
.br
.ti -1c
.RI "float \fBgetcx\fP () const"
.br
.ti -1c
.RI "float \fBgetcy\fP () const"
.br
.ti -1c
.RI "float \fBgetdx\fP () const"
.br
.ti -1c
.RI "float \fBgetdy\fP () const"
.br
.ti -1c
.RI "float \fBgetp1x\fP () const"
.br
.ti -1c
.RI "float \fBgetp1y\fP () const"
.br
.ti -1c
.RI "float \fBgetp2x\fP () const"
.br
.ti -1c
.RI "float \fBgetp2y\fP () const"
.br
.ti -1c
.RI "float \fBgetp3x\fP () const"
.br
.ti -1c
.RI "float \fBgetp3y\fP () const"
.br
.ti -1c
.RI "float \fBgetp4x\fP () const"
.br
.ti -1c
.RI "float \fBgetp4y\fP () const"
.br
.ti -1c
.RI "int \fBgetn\fP () const"
.br
.ti -1c
.RI "double \fBgetdt\fP () const"
.br
.ti -1c
.RI "bool \fBgetEnd\fP () const"
.br
.ti -1c
.RI "glm::vec4 \fBgetColor\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
