.TH "BlockAllocator< blockSize >" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockAllocator< blockSize >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockAllocator\fP (uint32_t size)"
.br
.ti -1c
.RI "void * \fBalloc\fP (uint32_t size)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
