.TH "BlockMapLoader::Region" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMapLoader::Region
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsegmentStart\fP"
.br
.ti -1c
.RI "uint32_t \fBstartPoints\fP"
.br
.ti -1c
.RI "\fBBoundRect\fP \fBbounds\fP"
.br
.ti -1c
.RI "double \fBbaseX\fP"
.br
.ti -1c
.RI "double \fBbaseY\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
