.TH "BlockMapLoader::BoundRect" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMapLoader::BoundRect
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBxMin\fP"
.br
.ti -1c
.RI "float \fBxMax\fP"
.br
.ti -1c
.RI "float \fByMin\fP"
.br
.ti -1c
.RI "float \fByMax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
