.TH "BlockMapLoader::NamedEntities" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMapLoader::NamedEntities
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnumNames\fP"
.br
.ti -1c
.RI "uint32_t \fBnameSizes\fP"
.br
.ti -1c
.RI "\fBNamedEntry\fP \fBentry\fP []"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
