.TH "BlockMapLoader::BlockMapHeader" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMapLoader::BlockMapHeader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnumNamedEntities\fP"
.br
.ti -1c
.RI "uint32_t \fBnumRegionContainers\fP"
.br
.ti -1c
.RI "uint32_t \fBnumRegions\fP"
.br
.ti -1c
.RI "uint32_t \fBnumSegments\fP"
.br
.ti -1c
.RI "uint32_t \fBnumPoints\fP"
.br
.ti -1c
.RI "uint32_t \fBdeltaEncoded\fP: 1"
.br
.ti -1c
.RI "\fBBoundRect\fP \fBbounds\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
