.TH "BlockMapLoader::RegionContainer" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMapLoader::RegionContainer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBstartRegion\fP"
.br
.ti -1c
.RI "uint32_t \fBendRegion\fP"
.br
.ti -1c
.RI "\fBBoundRect\fP \fBbounds\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
