.TH "BlockLoader::SecurityHeaderV1" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockLoader::SecurityHeaderV1
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBhash\fP [32]"
.br
.ti -1c
.RI "uint8_t \fBhash2\fP [32]"
.br
.ti -1c
.RI "uint8_t \fBsigid\fP [32]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
