.TH "BlockMapLoader::NamedEntry" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockMapLoader::NamedEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnameOffset\fP"
.br
.ti -1c
.RI "uint8_t \fBlen\fP"
.br
.ti -1c
.RI "uint8_t \fBentityType\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint32_t \fBoffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
