.TH "BlockLoader::Info" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockLoader::Info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBbytes\fP"
.br
.ti -1c
.RI "Type \fBt\fP"
.br
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
