.TH "ButtonWidget" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWidget2D\fP, and \fBWidget2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBButtonWidget\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, const std::string &text, float x, float y, float w, float h)"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.ti -1c
.RI "\fBButtonWidget\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, const std::string[]&text, float x, float y, float w, float h)"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
