.TH "Calendar" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calendar
.SH SYNOPSIS
.br
.PP
.PP
Inherits XDLTypeCalendar, and XDLTypeCalendar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalendar\fP (const char filename[])"
.br
.ti -1c
.RI "\fBCalendar\fP (const char filename[])"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
