.TH "CandlestickChartWidget" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CandlestickChartWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGraphWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCandlestickChartWidget\fP (\fBCanvas\fP *c, double x, double y, double w, double h)"
.br
.ti -1c
.RI "void \fBsetLineStyle\fP (const \fBStyle\fP *s)"
.br
.ti -1c
.RI "void \fBsetBoxStyle\fP (const \fBStyle\fP *s)"
.br
.ti -1c
.RI "void \fBsetBoxWidth\fP (double width)"
.br
.ti -1c
.RI "void \fBsetBoxColors\fP (const std::vector< glm::vec4 > &colors)"
.br
.ti -1c
.RI "void \fBsetBoxOutlineColors\fP (const std::vector< glm::vec4 > &colors)"
.br
.ti -1c
.RI "void \fBsetData\fP (const std::vector< double > &data)"
.br
.ti -1c
.RI "void \fBsetNames\fP (const std::vector< std::string > &names)"
.br
.ti -1c
.RI "void \fBcreateXAxis\fP (AxisType a=AxisType::TEXT) override"
.br
.ti -1c
.RI "void \fBcreateYAxis\fP (AxisType a) override"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
