.TH "Circle" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircle\fP (float x, float y, float rad, float angleInc, \fBStyle\fP *s)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
