.TH "ColorGrid" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorGrid
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColorGrid\fP (uint32_t xsize, uint32_t ysize)"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.ti -1c
.RI "void \fBrender\fP () override"
.br
.ti -1c
.RI "void \fBaddGrid\fP (float x0, float y0, float dx, float dy)"
.br
.ti -1c
.RI "void \fBaddRectangle\fP (float x, float y, float w, float h)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
