.TH "Color" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Color
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP (float r, float g, float b, float a)"
.br
.ti -1c
.RI "\fBoperator glm::vec4\fP () const"
.br
.ti -1c
.RI "\fBColor\fP \fBlighter\fP () const"
.br
.ti -1c
.RI "\fBColor\fP \fBdarker\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
