.TH "Combiner" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Combiner
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCombiner\fP (const char staticFileName[])"
.br
.ti -1c
.RI "void \fBparsePage\fP (int pageNum, const char dynamicFileName[])"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
