.TH "CompoundType" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompoundType
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXDLType\fP\&.
.PP
Inherited by \fBStruct\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompoundType\fP (const std::string &name)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
