.TH "CSPServlet" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSPServlet
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCSPTest1\fP, \fBCSPTest2\fP, \fBCSPTest3\fP, \fBCSPTest4\fP, \fBCSPTest5\fP, \fBCSPTest6\fP, and \fBCSPTest7\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrequest\fP (\fBRequest\fP &r)"
.br
.ti -1c
.RI "virtual void \fBrequest\fP (\fBCSPRequest\fP &r)=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBadd\fP (\fBCSPServlet\fP *s)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCSPRequest\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
