.TH "CSRGraph< VertexIndex_t, EdgeIndex_t, Weight_t >::VertexCount" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSRGraph< VertexIndex_t, EdgeIndex_t, Weight_t >::VertexCount
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVertexCount\fP (VertexIndex_t v, VertexIndex_t countAdj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "VertexIndex_t \fBv\fP"
.br
.ti -1c
.RI "VertexIndex_t \fBcountAdj\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
