.TH "CSVParser" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSVParser
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< std::vector< std::string > > \fBreadCSV\fP (const char filename[])"
.br
.RI "Read CSV file, Excel dialect\&. Accept 'quoted fields ''with quotes'''\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
