.TH "CTimer" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTimer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "double \fBelapsedSeconds\fP () const"
.br
.ti -1c
.RI "double \fBelapsedMillis\fP () const"
.br
.ti -1c
.RI "double \fBelapsedMicros\fP () const"
.br
.ti -1c
.RI "double \fBelapsedNanos\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
