.TH "CubicFunc" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CubicFunc
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBarcLength\fP () const"
.br
.ti -1c
.RI "double \fBsegmentLength\fP (int i) const"
.br
.ti -1c
.RI "double \fBderiv\fP (int i, double t) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
