.TH "Cursor" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cursor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCursor\fP (float x, float y, \fBStyle\fP *s, int id)"
.br
.ti -1c
.RI "void \fBinitIndices\fP ()"
.br
.ti -1c
.RI "void \fBprocess_input\fP (Inputs *in, float dt)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float \fBgetXPos\fP (int id)"
.br
.ti -1c
.RI "static float \fBgetYPos\fP (int id)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
