.TH "DocView" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DocView
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDocView\fP (\fBCanvas\fP *c, const \fBStyle\fP *style, const \fBDocument\fP *doc)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBprintPageNum\fP (uint32_t page)"
.br
.ti -1c
.RI "void \fBprint\fP (float x, float y, const \fBFont\fP *f, uint32_t v)"
.br
.ti -1c
.RI "void \fBadvance\fP ()"
.br
.ti -1c
.RI "void \fBadvance10\fP ()"
.br
.ti -1c
.RI "void \fBback\fP ()"
.br
.ti -1c
.RI "void \fBtop\fP ()"
.br
.ti -1c
.RI "void \fBbottom\fP ()"
.br
.ti -1c
.RI "void \fBgotoPage\fP (uint32_t pageNum)"
.br
.ti -1c
.RI "void \fBaddChar\fP (const \fBFont\fP *f, uint8_t c)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBprocess_input\fP (Inputs *in, float dt)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
