.TH "Ellipse" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ellipse
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEllipse\fP (float x, float y, float xRad, float yRad, float angleInc, \fBStyle\fP *s)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
