.TH "ESRIPolygon" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESRIPolygon
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBESRIShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBESRIPolygon\fP (SHPObject *shapePtr)"
.br
.ti -1c
.RI "std::vector< \fBESRIPoint\fP > \fBgetPoints\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
