.TH "Font::Glyph" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Font::Glyph
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlyph\fP (float advance, float bearingX, float bearingY, float sizeX, float sizeY, float u0, float u1, float v1, float v0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBadvance\fP"
.br
.ti -1c
.RI "float \fBbearingX\fP"
.br
.ti -1c
.RI "float \fBbearingY\fP"
.br
.ti -1c
.RI "float \fBsizeX\fP"
.br
.ti -1c
.RI "float \fBsizeY\fP"
.br
.ti -1c
.RI "float \fBu0\fP"
.br
.ti -1c
.RI "float \fBu1\fP"
.br
.ti -1c
.RI "float \fBv1\fP"
.br
.ti -1c
.RI "float \fBv0\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &s, const \fBFont::Glyph\fP &g)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
