.TH "FormServlet" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormServlet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHttpServlet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrequest\fP (\fBRequest\fP &r)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
