.TH "GapMinderWidget" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GapMinderWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWidget2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGapMinderWidget\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, float x, float y, float w, float h, const std::string &title, const \fBStyle\fP *titleStyle, const \fBStyle\fP *barStyle, float minX, float maxX, float minY, float maxY, float maxMultiplier, float minMultiplier, float tickSize, float tickStart, \fBScale\fP *yAxis, \fBScale\fP *xAxis)"
.br
.ti -1c
.RI "\fBGapMinderWidget\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, float x, float y, float w, float h)"
.br
.ti -1c
.RI "\fBGapMinderWidget\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, float x, float y, float w, float h, const std::vector< float > &xLocations, const std::vector< float > &yLocations)"
.br
.ti -1c
.RI "void \fBsetMinMaxY\fP (float min, float max)"
.br
.ti -1c
.RI "void \fBsetAxisScale\fP (\fBScale\fP *yAxis)"
.br
.ti -1c
.RI "void \fBsetTitleStyle\fP (const \fBStyle\fP *s)"
.br
.ti -1c
.RI "void \fBchart\fP (const std::vector< float > &yLocations, const std::vector< float > &xLocations, const std::vector< float > &sizes, int rulerInterval, const std::vector< glm::vec4 > &c)"
.br
.ti -1c
.RI "void \fBsetTitle\fP (const std::string &s)"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
