.TH "GenericList" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXDLType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericList\fP (const std::string &name, uint32_t size, const std::string &listType)"
.br
.ti -1c
.RI "DataType \fBgetDataType\fP () const override"
.br
.ti -1c
.RI "uint32_t \fBsize\fP () const override"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBBuffer\fP &buf) const override"
.br
.ti -1c
.RI "void \fBwriteMeta\fP (\fBBuffer\fP &buf) const override"
.br
.ti -1c
.RI "void \fBdisplay\fP (\fBBuffer\fP &binaryIn, \fBBuffer\fP &asciiOut) const override"
.br
.ti -1c
.RI "\fBXDLIterator\fP * \fBcreateIterator\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
