.TH "Graph" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCSRGraph< uint64_t, uint64_t, float >\fP, and \fBCSRGraph< VertexIndex_t, EdgeIndex_t, Weight_t >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBV\fP"
.br
.ti -1c
.RI "uint64_t \fBE\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
