.TH "GraphWidget" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSuperWidget2D\fP\&.
.PP
Inherited by \fBBarChartWidget\fP, \fBBoxChartWidget\fP, and \fBLineGraphWidget\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAxisType\fP { \fBLINEAR\fP, \fBLOGARITHMIC\fP, \fBTEXT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGraphWidget\fP (\fBCanvas\fP *c, \fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, double x, double y, double w, double h)"
.br
.ti -1c
.RI "virtual void \fBcreateXAxis\fP (AxisType a)=0"
.br
.ti -1c
.RI "virtual void \fBcreateYAxis\fP (AxisType a)=0"
.br
.ti -1c
.RI "void \fBsetGraphTitle\fP (std::string text)"
.br
.ti -1c
.RI "void \fBsetXAxisTextStyle\fP (const \fBStyle\fP *xAxisTextStyle)"
.br
.ti -1c
.RI "void \fBsetYAxisTextStyle\fP (const \fBStyle\fP *yAxisTextStyle)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAxisWidget\fP * \fBxAxis\fP"
.br
.ti -1c
.RI "\fBAxisWidget\fP * \fByAxis\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcommonRender\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBgraphTitle\fP"
.br
.ti -1c
.RI "const \fBStyle\fP * \fBxAxisTextStyle\fP"
.br
.ti -1c
.RI "const \fBStyle\fP * \fByAxisTextStyle\fP"
.br
.ti -1c
.RI "AxisType \fBxAxisType\fP"
.br
.ti -1c
.RI "AxisType \fByAxisType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
