.TH "HashMap< Val >::Iterator" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HashMap< Val >::Iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const \fBHashMap\fP &list)"
.br
.ti -1c
.RI "bool \fBoperator!\fP () const"
.br
.ti -1c
.RI "void \fBoperator++\fP ()"
.br
.ti -1c
.RI "const char * \fBkey\fP () const"
.br
.ti -1c
.RI "Val * \fBvalue\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
