.TH "HttpServlet" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HttpServlet
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBServlet\fP\&.
.PP
Inherited by \fBFormServlet\fP, and \fBTestHttpServlet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrequest\fP (\fBBuffer\fP &out)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
