.TH "Image" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImage\fP (\fBCanvas\fP *c, float x, float y, float width, float height, uint32_t textureID=0)"
.br
.ti -1c
.RI "\fBImage\fP (\fBCanvas\fP *c, float x, float y, float width, float height, const char *filePath, uint32_t textureID=0)"
.br
.ti -1c
.RI "void \fBaddImage\fP (const char *filePath)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
