.TH "InputEvent" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputEvent\fP (uint16_t userid, uint16_t input, uint16_t mods, uint16_t x, uint16_t y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint16_t \fBuserid\fP"
.br
.ti -1c
.RI "const uint16_t \fBinput\fP: 12"
.br
.ti -1c
.RI "const uint16_t \fBmods\fP: 4"
.br
.ti -1c
.RI "const uint16_t \fBx\fP"
.br
.ti -1c
.RI "const uint16_t \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
