.TH "Insertion" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Insertion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInsertion\fP (uint32_t offset, DataType d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint32_t \fBoffset\fP"
.br
.ti -1c
.RI "const DataType \fBd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
