.TH "LinearScale" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinearScale
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBScale\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBtransform\fP (double x) override"
.br
.ti -1c
.RI "void \fBinit\fP (double min, double max, double shift, double axisSize, double tickInterval) override"
.br
.ti -1c
.RI "float \fBnext\fP (float v) override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
