.TH "LogAxisWidget" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogAxisWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAxisWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogAxisWidget\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, double x, double y, double w, double h)"
.br
.ti -1c
.RI "void \fBsetBounds\fP (double minBound, double maxBound) override"
.br
.ti -1c
.RI "void \fBsetTickInterval\fP (double tickInterval) override"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
