.TH "MultiTransform" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultiTransform
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiTransform\fP (const glm::vec3 &pos=glm::vec3(1, 1, 1), const glm::vec3 &rot=glm::vec3(1, 1, 1), const glm::vec3 &scale=glm::vec3(1, 1, 1))"
.br
.ti -1c
.RI "void \fBsetPos\fP (const glm::vec3 &v)"
.br
.ti -1c
.RI "void \fBsetRot\fP (const glm::vec3 &v)"
.br
.ti -1c
.RI "void \fBsetScale\fP (const glm::vec3 &v)"
.br
.ti -1c
.RI "void \fBincrPos\fP (const glm::vec3 &v)"
.br
.ti -1c
.RI "void \fBincrRot\fP (const glm::vec3 &v)"
.br
.ti -1c
.RI "void \fBincrScale\fP (const glm::vec3 &v)"
.br
.ti -1c
.RI "glm::mat4 \fBgetModel\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
