.TH "NullGraphObserver" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NullGraphObserver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddVert\fP (uint32_t index, float x, float y, uint8_t initialVertColor, std::vector< \fBPoint\fP > &)"
.br
.ti -1c
.RI "void \fBaddEdge\fP (uint64_t i, float x1, float y1, float x2, float y2, uint32_t initialEdgeColor)"
.br
.ti -1c
.RI "void \fBupdateVert\fP (uint32_t i, uint8_t colorVal)"
.br
.ti -1c
.RI "void \fBupdateEdge\fP (uint64_t j, uint8_t colorVal)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
