.TH "ObjectHorizontalRenderer" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectHorizontalRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenderer\fP, and \fBRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdisplay\fP (\fBBuffer\fP &in, MultiShape2d *m, \fBMultiText\fP *t, float x0, float y0, float *w, float *h) const override"
.br
.ti -1c
.RI "virtual void \fBdisplay\fP (\fBBuffer\fP &in, MultiShape2d *m, \fBMultiText\fP *t, float x0, float y0, float *w, float *h) const override"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
