.TH "PageLayout" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PageLayout
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPageLayout\fP (float x0, float y0, float w, float h, float pageNumX, float pageNumY, float paragraphSpacing, uint32_t linesPerPage, const \fBFont\fP *f, float dropDead=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx0\fP"
.br
.ti -1c
.RI "float \fBx1\fP"
.br
.ti -1c
.RI "float \fBxDropDead\fP"
.br
.ti -1c
.RI "float \fBy0\fP"
.br
.ti -1c
.RI "float \fBy1\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.ti -1c
.RI "float \fBpageNumX\fP"
.br
.ti -1c
.RI "float \fBpageNumY\fP"
.br
.ti -1c
.RI "float \fBparagraphSpacing\fP"
.br
.ti -1c
.RI "uint32_t \fBlinesPerPage\fP"
.br
.ti -1c
.RI "const \fBFont\fP * \fBf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
