.TH "PageText" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PageText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiText\fP (const \fBStyle\fP *style, uint32_t size)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBloadText\fP (const char s[], uint32_t len)"
.br
.ti -1c
.RI "void \fBaddChar\fP (float x, float y, \fBFont\fP *f, const char c)"
.br
.ti -1c
.RI "void \fBadd\fP (float x, float y, const char s[], uint32_t len)"
.br
.ti -1c
.RI "void \fBadd\fP (float x, float y, uint32_t v)"
.br
.ti -1c
.RI "void \fBadd\fP (float x, float y, float v)"
.br
.ti -1c
.RI "void \fBadd\fP (float x, float y, double v)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBprocess_input\fP (Inputs *in, float dt)"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
