.TH "PositionDisplayer2D" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PositionDisplayer2D
.SH SYNOPSIS
.br
.PP
.PP
Inherits Widget2d\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPositionDisplay2D\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, uint32_t x, uint32_t y, uint32_t w, uint32_t h)"
.br
.ti -1c
.RI "void \fBaddPoint\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBmove\fP (int i, float x, float y)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
