.TH "Prefs" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prefs
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBload\fP ()"
.br
.ti -1c
.RI "void \fBsave\fP ()"
.br
.ti -1c
.RI "std::string \fBgetConfDir\fP () const"
.br
.ti -1c
.RI "std::string \fBgetFontDir\fP () const"
.br
.ti -1c
.RI "std::string \fBgetShaderDir\fP () const"
.br
.ti -1c
.RI "uint32_t \fBgetPreferredX\fP () const"
.br
.ti -1c
.RI "uint32_t \fBgetPreferredY\fP () const"
.br
.ti -1c
.RI "uint32_t \fBgetPreferredWidth\fP () const"
.br
.ti -1c
.RI "uint32_t \fBgetPreferredHeight\fP () const"
.br
.ti -1c
.RI "bool \fBgetFastLoadShaders\fP () const"
.br
.ti -1c
.RI "void \fBsetFastLoadShaders\fP (uint32_t fmt)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtrySavingShader\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
