.TH "Rectangle" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rectangle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape2D\fP\&.
.PP
Inherited by \fBButton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectangle\fP (\fBCanvas\fP *c, float x, float y, float width, float height, \fBStyle\fP *s)"
.br
.ti -1c
.RI "void \fBinitIndices\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
