.TH "Renderer" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renderer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBF64Renderer\fP, \fBF64Renderer\fP, \fBObjectHorizontalRenderer\fP, \fBObjectHorizontalRenderer\fP, \fBObjectNameValueRenderer\fP, \fBObjectNameValueRenderer\fP, \fBU32Renderer\fP, \fBU64Renderer\fP, \fBU64Renderer\fP, \fBVerticalListRenderer\fP, and \fBVerticalListRenderer\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDir\fP { \fBUP\fP, \fBDOWN\fP, \fBLEFT\fP, \fBRIGHT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdisplay\fP (\fBBuffer\fP &in, MultiShape2d *m, \fBMultiText\fP *t, float x0, float y0, float *w, float *h) const =0"
.br
.ti -1c
.RI "void \fBupdate\fP (Dir)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
