.TH "ScrollbarWidget" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScrollbarWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStyledMultiShape2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScrollbarWidget\fP (\fBCanvas\fP *c, const \fBStyle\fP *s, float x, float y, float w, float h)"
.br
.ti -1c
.RI "void \fBinit\fP () override"
.br
.ti -1c
.RI "void \fBrender\fP () override"
.br
.ti -1c
.RI "void \fBupdate\fP () override"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBscroll\fP (float dy)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
