.TH "Sector" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape2D\fP\&.
.PP
Inherited by \fBCircle\fP, \fBEllipse\fP, and \fBPolygon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSector\fP (\fBCanvas\fP *c, float x, float y, float xRad, float yRad, float fromAngle, float toAngle, float angleInc, \fBStyle\fP *s)"
.br
.ti -1c
.RI "void \fBinitIndices\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
