.TH "Servlet" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Servlet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Servlet\&.hh>\fP
.PP
Inherited by \fBHttpServlet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrequest\fP (\fBBuffer\fP &out)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
  Base class for servlet
  This is the common behavior between protocols such as HTTP and CSP
  so this is the low-level data methods.

  All servlets support a request, which is a client sending a message to

.fi
.PP
 the server requesting data\&. In HTTP, a request is ASCII with many potential lines if input, whereas in CSP it is a lot shorter, fixed format, and binary 
.PP
.nf
  @author: Dov Kruger

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
