.TH "ServletMap" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServletMap
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServletMap\fP (uint32_t initialSize=32768)"
.br
.ti -1c
.RI "void \fBadd\fP (const std::string &name, \fBHttpServlet\fP *s)"
.br
.ti -1c
.RI "\fBHttpServlet\fP * \fBget\fP (const char *s, size_t size) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
