.TH "Shapefile" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shapefile
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShapefile\fP (const char filename[])"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "SHPObject * \fBgetShape\fP (int index)"
.br
.ti -1c
.RI "std::vector< SHPObject * > \fBgetShapeVector\fP ()"
.br
.ti -1c
.RI "double * \fBgetMinBounds\fP ()"
.br
.ti -1c
.RI "double * \fBgetMaxBounds\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
