.TH "SocketIO" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketIO
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBsend\fP (socket_t sckt, const char *buf, int size, int flags)"
.br
.ti -1c
.RI "static int \fBrecv\fP (socket_t sckt, const char *buf, int size, int flags)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
