.TH "Stats1D< T >::Summary" 3 "Wed Jul 7 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stats1D< T >::Summary
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBmin\fP"
.br
.ti -1c
.RI "double \fBmax\fP"
.br
.ti -1c
.RI "double \fBq1\fP"
.br
.ti -1c
.RI "double \fBq3\fP"
.br
.ti -1c
.RI "double \fBmedian\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
