.TH "Struct::Member" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Struct::Member
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMember\fP (uint32_t nameOffset, uint32_t nameLen, const \fBXDLType\fP *type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBnameOffset\fP"
.br
.ti -1c
.RI "uint32_t \fBnameLen\fP"
.br
.ti -1c
.RI "const \fBXDLType\fP * \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
