.TH "Student" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Student
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStudent\fP (const std::string &first, const std::string &last, uint16_t id)"
.br
.ti -1c
.RI "uint32_t \fBserializeSize\fP () const"
.br
.ti -1c
.RI "std::string const \fBgetFirst\fP ()"
.br
.ti -1c
.RI "std::string const \fBgetLast\fP ()"
.br
.ti -1c
.RI "uint32_t const \fBgetID\fP ()"
.br
.ti -1c
.RI "char * \fBwrite\fP (char *p)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
