.TH "Tab" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tab
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTab\fP (\fBGLWin\fP *parent)"
.br
.ti -1c
.RI "\fBGLWin\fP * \fBgetParent\fP () const"
.br
.ti -1c
.RI "\fBTab\fP (const \fBTab\fP &orig)=delete"
.br
.ti -1c
.RI "\fBTab\fP & \fBoperator=\fP (const \fBTab\fP &orig)=delete"
.br
.ti -1c
.RI "\fBCanvas\fP * \fBaddCanvas\fP (const \fBStyle\fP *style, uint32_t vpX, uint32_t vpY, uint32_t vpW, uint32_t vpH)"
.br
.ti -1c
.RI "\fBCanvas\fP * \fBgetCanvas\fP (uint32_t i)"
.br
.ti -1c
.RI "\fBMainCanvas\fP * \fBgetMainCanvas\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.ti -1c
.RI "void \fBcleanup\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
