.TH "Text" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Text
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBShape\fP, and \fBShape2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBText\fP (float x, float y, \fBStyle\fP *style, const std::string &text)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.ti -1c
.RI "\fBText\fP (\fBGLWin\fP *w, float x, float y, const std::string &text)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBrender\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const uint32_t \fBLINE_LENGTH\fP = 256"
.br
.ti -1c
.RI "constexpr static uint32_t \fBLINE_LENGTH\fP = 256"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
