.TH "TextureArray" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureArray
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextureArray\fP (\fBShader\fP *shader, uint8_t allocSize=32)"
.br
.ti -1c
.RI "GLuint \fBloadImage\fP (const char *imagePath, uint8_t unit)"
.br
.ti -1c
.RI "GLuint \fBbindImage\fP (uint8_t unit)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
