.TH "U16" 3 "Tue Jul 6 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
U16
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXDLType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBU16\fP (uint16_t val=0)"
.br
.ti -1c
.RI "DataType \fBgetDataType\fP () const"
.br
.ti -1c
.RI "uint32_t \fBsize\fP () const override"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBBuffer\fP &buf) const"
.br
.ti -1c
.RI "void \fBdisplay\fP (\fBBuffer\fP &binaryIn, \fBBuffer\fP &asciiOut) const"
.br
.ti -1c
.RI "void \fBformat\fP (\fBBuffer\fP &binaryIn, \fBBuffer\fP &asciiOut, const char fmt[]) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBU16\fP &a, const \fBU16\fP &b)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
