.TH "U8" 3 "Thu Jul 1 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
U8
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBXDLType\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBU8\fP (uint8_t val=0)"
.br
.ti -1c
.RI "DataType \fBgetDataType\fP () const"
.br
.ti -1c
.RI "uint32_t \fBsize\fP () const override"
.br
.ti -1c
.RI "void \fBwrite\fP (\fBBuffer\fP &buf) const"
.br
.ti -1c
.RI "void \fBdisplay\fP (\fBBuffer\fP &binaryIn, \fBBuffer\fP &asciiOut) const override"
.br
.ti -1c
.RI "void \fBformat\fP (\fBBuffer\fP &binaryIn, \fBBuffer\fP &asciiOut, const char fmt[]) const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
