.TH "UDPV4Socket" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UDPV4Socket
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUDP4Socket\fP (const char *addr, uint16_t port)"
.br
.ti -1c
.RI "\fBUDP4Socket\fP (uint16_t port)"
.br
.ti -1c
.RI "void \fBlistenOnPort\fP ()"
.br
.ti -1c
.RI "void \fBwait\fP ()"
.br
.ti -1c
.RI "void \fBsend\fP (const char *buf, uint32_t len)"
.br
.ti -1c
.RI "void \fBsend\fP (uint32_t reqn)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
