.TH "UserId" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserId
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBU64\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserId\fP (uint64_t v)"
.br
.ti -1c
.RI "void \fBwriteMeta\fP (\fBBuffer\fP &buf) const override"
.br
.ti -1c
.RI "void \fBdisplay\fP (\fBBuffer\fP &binaryIn, \fBBuffer\fP &asciiOut) const"
.br
.ti -1c
.RI "void \fBformat\fP (\fBBuffer\fP &binaryIn, \fBBuffer\fP &asciiOut, const char fmt[]) const"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
