.TH "WebCursor" 3 "Thu Jul 8 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebCursor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWebCursor\fP (\fBCanvas\fP *c, \fBMultiShape2D\fP *s)"
.br
.ti -1c
.RI "\fBWebCursor\fP (\fBCanvas\fP *c, \fBMultiText\fP *m)"
.br
.ti -1c
.RI "void \fBaddText\fP (\fBStyle\fP *st, const char text[], uint32_t len)"
.br
.ti -1c
.RI "void \fBmoveRight\fP (float w, float h)"
.br
.ti -1c
.RI "void \fBmoveLeft\fP (float w, float h)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
