.TH "Widget2D" 3 "Mon Jul 5 2021" "Version 1.0" "Grail" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Widget2D
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAxisWidget\fP, \fBButtonWidget\fP, \fBButtonWidget\fP, \fBCandlestickChartWidget\fP, \fBGapMinderWidget\fP, and \fBSparklineWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWidget2D\fP (\fBStyledMultiShape2D\fP *m, \fBMultiText\fP *t, float x, float y, float w, float h)"
.br
.ti -1c
.RI "virtual void \fBinit\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBStyledMultiShape2D\fP * \fBm\fP"
.br
.ti -1c
.RI "\fBMultiText\fP * \fBt\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Grail from the source code\&.
